### ISSUE TITLE
Actually, there have been games that are decrypted

### ISSUE THREAD

**Issue by Mask-Ninja** [TylerJaacks/XBONEmu#1]
So, I found this post [not gonna link it] where someone found a Halo and another game's key. And with dev versions of apps, they use the key stored in the Gaming Services framework. I haven't played any games yet, I think you should make a GUI release of the PE loader.

**Comment by TylerJaacks** [comment]
I think I need to write a new PE Loader from scratch first. I was thinking of basing the executable loading code on the Wine project because it is similar to what I want to do to load an executable and stub the API calls.

**Comment by invasivelycoding** [comment]
Yes, it’s a console.

**Comment by Mask-Ninja** [comment]
Can't find one on the internet - I'd like an original one though - the only ones I can find are Series X kits and One S kits.

**Comment by Mask-Ninja** [comment]
You can't use the kits - they get banned.

**Comment by invasivelycoding** [comment]
Yeah, their certificates are renewed every 24 hours by microsoft and you will get very very lucky if theres one that isn't banned then even if it will get banned sooner or later once you connect to xbox live. You can find more than Series X and One S kits they're all over ebay.

**Comment by Mask-Ninja** [comment]
My dream now is to just get a 2013 One devkit and connect to the internet once, with one game, then make it offline and spend weeks trying to find a way to dump it.

**Comment by Mask-Ninja** [comment]
> I think I need to write a new PE Loader from scratch first. I was thinking of basing the executable loading code on the Wine project because it is similar to what I want to do to load an executable and stub the API calls.
> 
> Code can be found here at the Wine git mirror https://github.com/wine-mirror/wine/blob/master/loader/main.c and https://github.com/wine-mirror/wine/blob/master/loader/preloader.c
> 
> Also I am currently at my parents house and also I will be moving soon to a new apartment so I would like to try the Wine PE Loader path next. I lack the appropriate knowledge to to do this from scratch. Once I can't a simple homebrew app running built using the XDK, I will work on a simple UI.

I'm going to make a HTML concept if this, I'm bored and that's what I do.

**Comment by Mask-Ninja** [comment]
I'm actually really bad at coding apart from Scratch. Still haven't had time to really do this.

**Comment by dudebloke** [comment]
> Where is the XDK? I can't find the download anywhere - wait... is it a console?

adding onto this: Yes, there is a piece of software that also goes under the name XDK and there are leaked builds of XDK for building and testing xbox one software floating around online.

**Comment by Mask-Ninja** [comment]
Just to clear this up, the XDK (Xbox Development Kit) has been around since 2001. It is a console, but there is GDK software out there. What I said up there is probably all false, it's only a private key leak. I still am researching but now understand how stupid I was back then.

**Comment by Mask-Ninja** [comment]
And close, no they haven't, I mean I know someone _that has_, but generally, no.
